import { Inter } from "next/font/google";
import "./globals.css";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogOutBtn from "./LogOutBtn";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions) //서버컴포넌트,서버기능 안에서 사용가능한 함수
  console.log(session)
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          {session ? <LogOutBtn/> : <LoginBtn/>}
        </div>
        {children}
      </body>
    </html>
  );
}
