import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="flex gap-0 justify-between self-stretch px-10 py-3 border-b border-gray-200 border-solid max-md:flex-wrap max-md:px-5 bg-[#111827]">
          <div className="flex gap-4 my-auto text-lg font-bold tracking-tight text-white">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/41c658445cf69a59e2de6eaed6d982017da3519daa9a5896c8ce3139cb759742?apiKey=9d9828c90f724a1aaaf800f0335e4543&"
              className="shrink-0 my-auto w-4 aspect-square"
            />
            <a href="/">Doge Forecast</a>
          </div>
          <div className="flex gap-5 pl-20 max-md:flex-wrap">
            <div className="flex gap-5 justify-between py-2.5 text-sm font-medium leading-5 text-white max-md:flex-wrap">
              <a href={'/news'}>News</a>
              <a href={'/community'}>Community</a>
              <a href='/login'>Login</a>
            </div>
          </div>
        </div>
        
        {children}
      
      
      </body>
    </html>
  );
}
